name = "farmforge"
main = "src/worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "db01"
database_id = "2010096c-9614-459c-83db-843a9e32d552"
